image: privacybydesign/node_yarn_python3:latest

stages:
  - build

before_script:
  - set -euxo pipefail
  - git clone https://github.com/privacybydesign/pbdf-schememanager.git
  - git clone https://github.com/privacybydesign/irma-demo-schememanager.git
  - yarn install --frozen-lockfile

build:
  stage: build
  artifacts:
    # Disabling artifact expiry is not supported yet, so make
    expire_in: 100 year
    paths:
      - nl/
      - en/
      - pbdf-schememanager/
      - irma-demo-schememanager/
      - script.js
      - style.css
      - index.json
  script:
    - yarn run build
    - python3 update.py
