image: privacybydesign/python3:latest

stages:
  - build

before_script:
  - set -euxo pipefail
  - git clone https://github.com/privacybydesign/pbdf-schememanager.git
  - git clone https://github.com/privacybydesign/irma-demo-schememanager.git

build:
  stage: build
  artifacts:
    paths:
      - nl/
      - en/
      - pbdf-schememanager/
      - irma-demo-schememanager/
      - script.js
      - style.css
      - index.json
  script:
    - python3 update.py
